### ISSUE TITLE
Use a lower-level library to implement requests in C++

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#12]
Libcurl does not give me the autonomy I would require and even if it is still faster than python it is still not as fast as expected.

**Comment by heidihoward** [comment]
Library-wise @achamayou suggested [libuv](https://github.com/libuv/libuv) and [llhttp](https://github.com/nodejs/llhttp) which are already used in CCF

**Comment by fotiskoun** [comment]
That's very helpful to have a first look. Thank you!

**Comment by heidihoward** [comment]
I believe this has been done by PR https://github.com/fotiskoun/CCF/pull/13. Ready to close this issue?

**Comment by fotiskoun** [comment]
Sure.
