### ISSUE TITLE
Clear code from the comments of past submitter implementations, edit cmake and fix ci-checker issues

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#15]
Remove any older code that is no longer needed from the licurl and libuv implementations. Reshape CMakeLists.txt as well including directories only instead of separate files and try targeting libs instead of files.

**Comment by fotiskoun** [comment]
Fix the `ci-scripts` check as well because it breaks due to new absolute path in public headers.

**Comment by heidihoward** [comment]
Well done @fotiskoun! This is much better after PR https://github.com/fotiskoun/CCF/pull/27!

There's still a few things to do in this regard, for instance, removing your local file paths from the `CMakeLists.txt`, removing/moving commented out code and removing the `stdcpp.h`.

**Comment by fotiskoun** [comment]
Thanks! I will create a new issue for these comments. But let me ask some questions first

- For the local paths, I can delete them but I would need to find a way to automatically install parquet and arrow. Maybe having a script that will install parquet and arrow before one runs cmake?
- About stdcpp.h I couldn't find a way to `include <bits/stdc++.h>` without throwing an error during compilation. I couldn't find out what is the issue with clang and `stdc++.h`. That is why I kept it but by renaming it to `stdcpp.h` as `ci-scripts`  formatter was complaining?
- Do you refer to any particular commented code, as I think I removed everything from the submitter. (There is still some in the loggin_generator but I will split it in the future to other_apps_generator files)

**Comment by heidihoward** [comment]
I think this can be closed once https://github.com/fotiskoun/CCF/tree/add-arrow-on-ansible is merged

**Comment by fotiskoun** [comment]
I have created a new issue for clearing stdcpp, as the other two notes are now addressed I closed this issue
