### ISSUE TITLE
Server address in the submitter arguments

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#19]
The server address until now was drawn from the requests in generation. Although, in raw requests the `host: 127.0.0.1:8000` could be omitted.

**Comment by fotiskoun** [comment]
@heidihoward could you let me know which is best? 
1. Keep the `host` header in the request created by the generator and make submitter to get the server address from this header?
2. Add as a command line argument when executing submitter, the server address and remove the `host` header?
3. Or both, i.e. have the `host` header in the request and the submitter get the server address from a command line argument?

**Comment by heidihoward** [comment]
Option 2, just a command line argument to the submitter

**Comment by heidihoward** [comment]
just to clarify, CCF does not require the host header in HTTP/1.1 requests?

**Comment by fotiskoun** [comment]
I am very sure I was able to submit successfull requests without have the host header. I can always check again, although the generator produces this header now.
