### ISSUE TITLE
Show performance breakdown by request type

### ISSUE THREAD

**Issue by heidihoward** [fotiskoun/CCF#26]
It would be great if the anaylser took the parquet file from the generator and used it to show a performance breakdown by request type

**Comment by fotiskoun** [comment]
@heidihoward let's say there is the following series of requests: 1 GET count, 10 POST data, 1 GET count, 100 GET data, 5 DELETE, 1 GET count, 50 GET data
Should there be:
1.  Analysis for each of the three type of requests? 3 in total 
2. Analysis for each type of request and path? So 1 for GET data, 1 for GET count, 1 for POST, 1 for DELETE
3. Analysis for every changing type and request? So, 1 for GET count, 1 for POST, 1 for GET count+data (or 1 for GET count and 1 for GET data), 1 for DELETE etc.

I think (1) makes more sense than the others but I am not sure if you would prefer a separate analysis for the same request verb  for different paths.

**Comment by heidihoward** [comment]
I would suggest providing the tools for (2) in the anaylser library but just doing (1) in the command line tool

**Comment by heidihoward** [comment]
Done in https://github.com/microsoft/CCF/pull/5264
