### ISSUE TITLE
add arrow on ansible

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#36]
add arrow and parquet on ansible workflow to replace the hardcoded name in cmake and then PR in CCF the ansible change

**Comment by heidihoward** [comment]
Even though I cannot run the c++ submitter at the moment, if you are happy with the changes then I suggest you merge them into  ` testing-performance-system`  and we can debug my issues separately. 

@fotiskoun If you need easy access to a clean machine to test this on, then I suggest you try using codespaces (go to the branch on github and then go to the green code button -> codespaces tab -> create new codespace)

**Comment by heidihoward** [comment]
I think this can be closed as soon as https://github.com/fotiskoun/CCF/tree/add-arrow-on-ansible is merged as this seems to be working!

**Comment by fotiskoun** [comment]
Yes, it is working, made a few last changes on readme, deleted old cmake files and it is now merged. So, this issue can now close and rest in peace.
