### ISSUE TITLE
Create a PR in CCF for the Analyzer

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#41]

**Comment by heidihoward** [comment]
Wonderful! 

Might be useful to decide what order you'd like to submit these CCF PRs and what changes (if any) are needed to analyzer before the PR

**Comment by fotiskoun** [comment]
I think that at least for the analyzer, I first need to break it as a python library before I make any PR to CCF. Let's call this issue then blocked by https://github.com/fotiskoun/CCF/issues/43

**Comment by heidihoward** [comment]
https://github.com/microsoft/CCF/pull/4509
