### ISSUE TITLE
Make analyzer as a python library

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#43]

**Comment by heidihoward** [comment]
Sounds great! Would be cool if you could keep the cli too (like you did with the generator)

**Comment by fotiskoun** [comment]
Yes that's my plan, 1 file for the cli and I will also have a sample file as a use of the different analyzer functions and I will look at jupyter, too

**Comment by fotiskoun** [comment]
Connections to https://github.com/fotiskoun/CCF/pull/51
