### ISSUE TITLE
Replace python submitter aiohttp to httpx

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#46]
The python submitter needs to work with most use cases instead of being fast. Aiohttp while comes very handy and is fast is better to be replaced with httpx that can support http1 and http2. So, replace that in python submitter.

**Comment by fotiskoun** [comment]
@heidihoward I would like to know if you are ok with this issue. This issue was generated by trying to test lskv-generator  from https://github.com/fotiskoun/CCF/issues/44
I think it is more sensible to have a python submitter (httpx) that works with http1 and http2 instead of a slightly faster, but not as fast as C++, submitter(aiohttp).

**Comment by heidihoward** [comment]
Good with me

**Comment by heidihoward** [comment]
As an aside, I would not spend too much time on the python submitter as the idea (as I understand it) is that the c++ submitter will be the main submitter
