### ISSUE TITLE
Reach for a single client the highest throughput 

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#5]
Send as much traffic as possible to the server and ensure that the client is not adding delays.
1) Find other servers that support pipelining and test the submitter there
-It gets higher throughput: then it is the server's issue that cannot increase throughput
-It gets the same throughput: it is most probably the client's issue that cannot support higher throughput and add delay
-It get less  throughput: you couldn't be sure as the mock server cannot accept high traffic
2) Use a profiling tool to check the c++ submitter
3) Use a new way to send requests to compare with libcurl

**Comment by heidihoward** [comment]
I believe this can be closed right?

**Comment by fotiskoun** [comment]
Yes I was thinking the same. I think that the current results I attach below for the cpp loggin application in an azure machine look good for now:
compile_target=virtual, 100.000 get requests:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/37985618/200411143-cd3cd1f0-557c-4156-83ba-fa39df13c047.png">

compile_target=sgx, 100.000 get requests:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/37985618/200412425-512ecddd-6cfe-4122-85f0-0a630cbfdbc0.png">
