### ISSUE TITLE
installing python requirements adds crypto warning

### ISSUE THREAD

**Issue by fotiskoun** [fotiskoun/CCF#57]
Find which of the pip requirements inserts the issue and work around that

**Comment by fotiskoun** [comment]
It is probably an issue that my testing-performance branch was split before  the [CCF cryptography update](https://github.com/microsoft/CCF/commit/957e3bc5beba6df646a66ef76757657fdd18b3aa)

**Comment by heidihoward** [comment]
Agreed. This should be fixed by syncing your `testing-performance` branch with CCF's `main`

**Comment by fotiskoun** [comment]
After merging syncing `CCF:main` to `fotiskoun:main` and merge `main` to `testing-performance-system` the warning was resolved. I close this issue.
